In [17]:
import math
import numpy as np
import numpy.linalg as la
import pandas as pd
import matplotlib.pyplot as plt

In [37]:
covariance = pd.read_excel("covariance_matrix.xls")
covariance

Bond Market  Growth Fund  Metal Fund  Stock Market  Value Fund  \
0     1.000271    -0.000165    0.000422     -0.000305   -0.000175   
1    -0.000165     1.010713    0.010735      0.007441    0.009745   
2     0.000422     0.010735    1.024614      0.006975    0.009980   
3    -0.000305     0.007441    0.006975      1.006736    0.007029   
4    -0.000175     0.009745    0.009980      0.007029    1.009283   
5     0.000237     0.007536    0.008250      0.007345    0.007224   

   Admiral Shares  
0        0.000237  
1        0.007536  
2        0.008250  
3        0.007345  
4        0.007224  
5        1.014327

# Question 1: Compute the optimal Sharpe ratio portfolio of the first six funds in the usual manner, except add 1 to all diagonal elements of the covariance matix and shrink all average returns halfway to the return that would give a Sharpe ratio of 0.5.

In [52]:
mean_excess_return = [0.00693333,0.01269583,-0.00539583,0.01824375,0.0053625,0.01521875]
optimal_weight = np.matmul((np.linalg.inv(covariance)),mean_excess_return)

sum_weight = 0;
for i in range (6):
    sum_weight +=optimal_weight[i]

optimal_weight = optimal_weight/sum_weight
optimal_weight

array([ 0.1351955 ,  0.24028143, -0.11083237,  0.34933361,  0.09782671,
        0.28819513])

# Question2: Compute an optimal Black-Litterman portfolio using market cap weights of 5 (Bonds), 2 (International Growth), 1 (Metals), 5 (Stocks), 2 (International Value) and 3 (REIT) and moderate confidence in the following views: International Growth and Value will each beat Stocks by 2% per year, Bonds will have a 0% return, the return on Metals will be the opposite of the return on Bonds, Real Estate will have the average return of Stocks and Metals; all views independent. At all times, try to do the reasonable thing to get a reasonable portfolio result.

In [95]:
#we choose lambda to be 3.07
cap_weight = np.array([5.00, 2.00, 1.00, 5.00, 2.00, 3.00])
sum_weight = 0
for i in range (6):
    sum_weight += cap_weight[i]
cap_weight = cap_weight/sum_weight

lambda_model = 3.07
implied_excess_return = lambda_model*np.matmul(covariance,cap_weight)
implied_excess_return

array([0.85282605, 0.35998121, 0.19234897, 0.86814569, 0.35884514,
       0.53190496])

In [96]:
Q = np.array([[2],[0],[0],[1]])
P = np.array([[0,0.5,0,-1,0.5,0],[1,0,0,0,0,0],[0,0,1,0,0,0],[0,0,0,0,0,1]])

omega = np.zeros((4,4))
scalar_tow = 0.025
for i in range(4):
    omega[i][i] = scalar_tow*np.matmul(P[i],np.matmul(covariance,P[i].transpose()))

In [97]:
expected_return = np.linalg.inv(np.linalg.inv(scalar_tow*covariance) + np.matmul(P.transpose(),np.matmul(np.linalg.inv(omega),P)))
expected_return_second = np.matmul(np.linalg.inv(scalar_tow*covariance), implied_excess_return.reshape((-1,1)))+ np.matmul(P.transpose(),np.matmul(np.linalg.inv(omega),Q))  
expected_return = np.matmul(expected_return,expected_return_second)
expected_return

array([[0.42647652],
       [0.78068007],
       [0.09845059],
       [0.03454134],
       [0.77929563],
       [0.76552022]])